
---
  - name: Initial server setup
    hosts: all
    become: yes

    tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install JRE
      apt:
        name: openjdk-8-jre-headless
        state: latest

    - name: Install Certbot
      apt:
        name: certbot
        state: latest

    - name: Install Mysql
      apt:
        name: mysql-server-8.0
        state: latest
    # Restart required?
    - name: Check if reboot required
      stat: 
        path: /var/run/reboot-required
      register: reboot_required_file

    # Initate system restart
    - name: Reboot if required
      reboot:
        msg: "Reboot initiated by Ansible due to system updates"
        reboot_timeout: 5400
      when: reboot_required_file.stat.exists == true