
---
  - name: Initial server setup
    hosts: all
    become: yes

    tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install JRE
      apt:
        name: openjdk-8-jre-headless
        state: latest

    - name: Install Certbot
      apt:
        name: certbot
        state: latest

    - name: Install Mysql
      apt:
        name: mysql-client-8.0
        state: latest