
---
- name: Create MySQL user and grant
  hosts: all
  become: yes
  vars_files:
    - ../variables/variables.yml
    - ../variables/mysql_conf.yml

  tasks:
  - name: Create a new database
    shell: mysql -u {{ db_admin }} -h {{ host }} -P 3306 -p{{ password }}  -e "{{ EXEC_create_db}}"
    #no_log: True

  - name: Create a new user
    shell: mysql -u {{ db_admin }} -h {{ host }} -P 3306 -p{{ password }}  -e "{{ EXEC_create_user}}"
    #no_log: True

  - name: Grant PRIVILEGES
    shell: mysql -u {{ db_admin }} -h {{ host }} -P 3306 -p{{ password }}  -e "{{ EXEC_grant}}"
    #no_log: True

  - name: Install Mysql
    apt:
      name: mysql-client-8.0
      state: absent