
---
  - name: Create user & group for running project
    hosts: all
    become: yes
    vars_files:
      - ../variables/variables.yml

    tasks:
    - name: Create group
      group:
        name: "{{ project_root }}"

    - name: Create user for webserver
      user:
        name: "{{ username }}"
        group: "{{ groupname }}"
        home: "{{ group_home }}"